export const globalActionType = {
  SAVE_TOKEN: "SAVE_TOKEN",
  SHOW_UPDATE_WELCOME_PAGE: "SHOW_UPDATE_WELCOME_PAGE",
  SAVE_OPT_DATA: "SAVE_OPT_DATA",
  SAVE_USER_DATA: "SAVE_USER_DATA",
  LOGOUT: "LOGOUT",
};
